version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel8:latest

dependencies:
  python:
    - requests
    - hvac
  galaxy:
    collections:
      - community.crypto
      - community.hashi_vault
      - cisco.ios

additional_build_steps:
  prepend:
    - RUN microdnf install -y git