version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  python:
    - requests
    - hvac
  galaxy:
    collections:
      - community.crypto
      - community.hashi_vault
      - cisco.ios

# additional_build_steps:
#   prepend:
#    - RUN microdnf install -y git